### ISSUE TITLE
Must be built against Root v5-xx-xx

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/CommandLineInterface#3]
Just a heads up, this only builds correctly against Root v5-xx-xx. I built it against v5-35-36 and it worked fine. If it is built against Root v6-xx-xx it cannot find the libPhysics directory.

**Comment by SmithJK** [comment]
Does the close mean you figured out how to compile against root 6?

**Comment by cnatzke** [comment]
No, I just figured out I should close it since I got it to compile. I compiled against v5.
